TWILIO_SID = "YOUR_TWILIO_SID"
TWILIO_AUTH = "YOUR_TWILIO_AUTH"
WHATSAPP_FROM = "whatsapp:+14155238886"
WHATSAPP_TO = "whatsapp:+61XXXXXXXXX"

ALPACA_API_KEY = "YOUR_API_KEY"
ALPACA_SECRET = "YOUR_SECRET"
ALPACA_BASE_URL = "https://paper-api.alpaca.markets"